version: '3.5'
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb:mmesbahi
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network
    restart: always

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx:mmesbahi
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my-network
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress:mmesbahi
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    networks:
      - my-network
    restart: always


networks:
  my-network:
    driver: bridge
volumes:
  wordpress-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${WP_VOL}
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOL}
